#!/usr/bin/env bash
# author: Tolga MALKOC | ghostlexly@gmail.com

scriptdir=$(dirname $0)

# check dependencies
check_dependencies() {
	if [ ! "$(which mpv)" ] || [ ! "$(which pcregrep)" ] ; then
		echo "Missing dependencies. Do you wish to install them? [y/n]"
		read input
		if [ "$input" == "y" ] ; then
			sudo apt install mpv pcregrep
		else
			echo "Dependencies unfulfilled, aborting."
			exit 1
		fi
	fi
}
check_dependencies


# get arguments
print_help() {
    echo "Usage: gpu-video-wallpaper video_path.mp4"
    echo ""
}

if [ $# = 0 ]
    then print_help
        exit 1
fi

while true
    do if [ $# -gt 0 ]
        then case $1 in
            --*)
                print_help
                exit 1
            ;;
            *)
                break
            ;;
        esac
    else
        echo "No video path given!"
        exit 2
    fi
done

VIDEO_PATH="$1"
SCREENS=`xrandr | grep " connected\|\*" | pcregrep -o1 '([0-9]{1,}[x]{1,1}[0-9+]{1,}) \('`

for item in $SCREENS
do
    $scriptdir/xwinwrap -g $item -fdt -ni -b -nf -un -o 1.0 -- mpv -wid WID --loop --no-audio $VIDEO_PATH & disown
done